[package]
name = "gps_mocker"
version = "2.1.0"
description = "Send Mocked GPS to Android/iOS devices"
authors = [ "Akylas <dev@akylas.fr>" ]
license = "MIT"
repository = "https://github.com/Akylas/gps-mocker-rs"
default-run = "gps_mocker"
edition = "2021"
build = "src/build.rs"

[lib]
name = "gps_mocker_lib"
crate-type = [ "staticlib", "cdylib", "rlib" ]

[build-dependencies]
tauri-build = { version = "2", features = [ ] }

[dependencies]
log = "0.4.15"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "2", features = [ ] }
tauri-plugin-shell = "2"
tauri-plugin-os = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dev-dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-window-state = "2"
reqwest = { version = "0.12", default-features = false, features = [ "rustls-tls", "json" ] }

[target."cfg(target_os = \"android\")".dependencies]
tauri-plugin-mock-location = { path = "plugins/tauri-plugin-mock-location" }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
cocoa = "0.24"
objc = "0.2"

  [target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies.rusty_libimobiledevice]
  features = [ "static", "vendored" ]
  path = "vendor/rusty_libimobiledevice"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
